### ISSUE TITLE
Maquette du site Kozea Group

### ISSUE THREAD

**Issue by liZe** [Kozea/kozea#37]

**Comment by piline** [comment]
-  [ ] accueil
-  [ ] about
-  [ ]  activité
-  [ ]  expertise
-  [ ]  contact

**Comment by piline** [comment]
- about : https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbbWNxVXBtaGV6bmM/view?usp=sharing
- activité : https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbc1A5ZlRKSkEzeFE/view?usp=sharing
- contact : https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbMXAxVllVb1pZTTQ/view?usp=sharing
