### ISSUE TITLE
Faire la brochure de Jean-Pierre en s'inspirant de la présentation

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/kozea#61]
Reprendre cette présentation :

https://docs.google.com/presentation/d/1ub4B_KG-8-fInmDRfX0W5ySzo4x3UoSkhM8bexXHxeA/edit#slide=id.p

**Comment by Maxouuu** [comment]
La brochure : 

https://docs.google.com/a/kozea.fr/presentation/d/17ya2SAI2SjmTJWYdJXWW2agcM2cs2bUYi1yuzzTtn0E/edit?usp=sharing

@hugobernard fera le style.
