### ISSUE TITLE
Résoudre les problèmes sur la page LinkedIn

### ISSUE THREAD

**Issue by Maxouuu** [Kozea/kozea#71]
- [x] mailer LinkedIn pour changer l'URL (avec KOZEA)
- [x] changer le nom de la page : mettre KOZEA group

**Comment by Nawrid** [comment]
j'ai fait une demande auprès de LinkedIn ce jour directement via leur formulaire de contact j'attends leur réponse, je vous tiens informé

**Comment by Nawrid** [comment]
Le lien a été mis à jour : http://www.linkedin.com/company/kozeagroup  
je vais voir s'il y a moyen de désindexer les anciens liens auprès de LinkedIn ou de Google directement

**Comment by Nawrid** [comment]
Google va désindexer les pages automatiquement :-)
